version: '3.7'

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app/
      - cache_vendor:/app/vendor
    tty: true

volumes:
  cache_vendor: